/**
 * PRIME DISpatch — Tailwind v4 CSS-first token config
 * Generated by Style Dictionary v4 + DTCG 2025.10
 * Ratified against CD2 (representation/visual-system/color.md)
 * Do not hand-edit; regenerate via `npm run build`.
 */

import type { Config } from "tailwindcss";

export default {
  theme: {
    extend: {
      colors: {
        platform: {
          accentPrime: "oklch(0.51 0.20 27)",
          wordmark: {
            dis: "oklch(0.51 0.20 27)",
            patch: "oklch(0.21 0.006 56)"
          },
          text: {
            body: {
              strong: "oklch(0.21 0.006 56)"
            }
          }
        },
        dispatch: {
          vellum: {
            "25": "oklch(0.99 0.012 88)",
            "50": "oklch(0.985 0.018 87)",
            "100": "oklch(0.96 0.025 85)",
            "200": "oklch(0.92 0.040 82)",
            "300": "oklch(0.87 0.055 78)"
          },
          lane: {
            editorial: { strong: "oklch(0.55 0.16 41)" },
            institutional: { strong: "oklch(0.41 0.043 257)" },
            dispatch: { strong: "oklch(0.51 0.20 27)" }
          },
          chrome: {
            "sky-high": "oklch(0.99 0.012 88)",
            "sky-low": "oklch(0.96 0.025 85)",
            reflect: "oklch(0.92 0.040 82)",
            "window-warm": "oklch(0.87 0.055 78)"
          }
        },
        asset: {
          cartography: { pulse: "oklch(0.45 0.18 22)" }
        }
      }
    }
  }
} satisfies Config;
